spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 84948494
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??